production:
  :action_controller:
      :session:
        :secret:  hash_for_your_sessions
  :action_mailer:
      :delivery_method: :smtp
      :smtp_settings:
        :address: smtp.domain.com
        :port: 25
        :authentication: plain
        :user_name: username@domain.com
        :password: password
        :domain: domain.com
        :perform_deliveries: true
  :default_host: domain.com
  :bitly: 
      :login: some_login
      :api_key: bitly_api_key
  :google:
      :analytics_user_id: google_analytics_code
      :verification_code: google_webmaster_verification_code
      :custom_search_key: google_custom_search_code
  :cron_job_code: secret_key_to_access_the_cronjob
  :gateway:
      :login: login_to_payment_gateway
      :password: password_to_payment_gateway
  :recaptcha:
      :public_key: public_key
      :private_key: private_key
  :hoptoad:
      :api_key: some_obscure_key
  :s3_bucket:
      :production: name-for-production-storage
      :staging: name-for-staging-storage
      :development: name-for-development-storage
  :site:
      :info_account_email: email_of_the_info_account_at_the_site
  :facebook:
      :consumer_key: api_key
      :consumer_secret: application_secret
  :paperclip:
      :storage: :s3
      :s3_credentials: <%= "#{RAILS_ROOT}/config/s3.yml" %>
      :bucket: <%= S3_BUCKET %>
      :path_prefix: ""
      :url_prefix: ""
  :email_notifications:
      :editor:
        :email: "david@spot.us"
        :name: "David Cohn"
      :info:
        :email: "info@spot.us"
        :name: "Spot.Us"
      :webmaster:
        :email: "webmaster@spot.us"
        :name: "Webmaster Spot.Us"
  :customization:
    :css_file: 
    :site_name: "Spot.Us"
    :facebook_url: "http://www.facebook.com/pages/SpotUs/74947774190"
    :twitter_url: "http://twitter.com/spotus"
    :flickr_url: "http://www.flickr.com/photos/29792566@N08/"
    :blog_url: "http://blog.spot.us"
